linters:
  disable-all: true
  enable:
  - deadcode
  - gocyclo
  - golint
  - gosec
  - govet
  - ineffassign
  - misspell
  - staticcheck
  - errcheck
  - unused
  - gosimple
  - varcheck

linters-settings:
  gofmt:
    simplify: false
  gosec:
    excludes:
    - G404 # G404: Use of weak random number generator (math/rand instead of crypto/rand)

run:
  timeout: 5m