linters:
  disable-all: true
  enable:
  - deadcode
  - gocyclo
  - golint
  - gosec
  - govet
  - ineffassign
  - misspell
  - staticcheck
  - errcheck
  - unused
  - gosimple
  - varcheck

linters-settings:
  gofmt:
    simplify: false

run:
  timeout: 5m