services:
  db:
    image: postgres-pg-partman:latest
    build:
      context: ./postgres
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"

  redis:
    # Azure cache for Redis supports 6.0 only
    image: redis:6.0.20
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    environment:
      discovery.type: single-node
    ports:
    - "9200:9200"
    - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

  proxy:
    # nginx has mainline (1.odd_minor_version) and stable (1.even_minor_version) release.
    # We use stable here.
    image: nginx:stable
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
    - ./tls-key.pem:/etc/nginx/tls-key.pem
    - ./tls-cert.pem:/etc/nginx/tls-cert.pem
    ports:
    - "8000:8000"
    - "8010:8010"
    - "3100:3100"
    - "443:443"

  ldap:
    profiles: ["ldap"]
    image: bitnami/openldap:2.6
    ports:
    - "1389:1389"
    - "1636:1636"
    volumes:
    - openldap_data:/bitnami/openldap
    environment:
      LDAP_ADMIN_USERNAME: "admin"
      LDAP_ADMIN_PASSWORD: "adminpassword"
      LDAP_ADMIN_DN: "cn=admin,dc=example,dc=org"
      LDAP_ROOT: "dc=example,dc=org"

  phpldapadmin:
    profiles: ["ldap"]
    image: osixia/phpldapadmin:stable
    ports:
    - "18080:80"
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "#PYTHON2BASH:[{'ldap': [{'server': [{'tls': False}, {'port': 1389}]},{'login': [{'bind_id': 'cn=admin,dc=example,dc=org'},{'bind_pass': 'adminpassword'}]}]}]"
      PHPLDAPADMIN_HTTPS: "false"
      PHPLDAPADMIN_LDAP_CLIENT_TLS: "false"

volumes:
  redis_data:
    driver: local
  db_data:
    driver: local
  elasticsearch_data:
    driver: local
  openldap_data:
    driver: local
