name: Build image
inputs:
  target:
    required: true
  image_name:
    required: true
  push_image:
    required: true
  build_arch:
    required: true
  docker_registry:
    required: false
  docker_username:
    required: false
  docker_password:
    required: false
outputs:
  image_digest:
    value: ${{ steps.build_image.outputs.image_digest }}
runs:
  using: "composite"
  steps:
  - name: Install qemu for multi arch build
    shell: bash
    run: docker run --privileged --rm tonistiigi/binfmt --install all
  - name: Setup container builder
    shell: bash
    run: |
      docker buildx create \
        --name container-builder \
        --driver docker-container \
        --bootstrap --use
  - name: docker login
    if: ${{ inputs.push_image == 'true' }}
    env:
      DOCKER_USERNAME: ${{ inputs.docker_username }}
      DOCKER_PASSWORD: ${{ inputs.docker_password }}
      DOCKER_REGISTRY: ${{ inputs.docker_registry }}
    shell: bash
    run: |
      printf "$DOCKER_PASSWORD" | docker login --password-stdin --username "$DOCKER_USERNAME" $DOCKER_REGISTRY
  - id: build_image
    run: |
      make build-image \
        BUILD_ARCH=$BUILD_ARCH \
        OUTPUT=type=image,name=$IMAGE_NAME,push-by-digest=true,name-canonical=true,push=true \
        TARGET=$TARGET \
        IMAGE_NAME=$IMAGE_NAME \
        METADATA_FILE=metadata.json
      DIGEST="$(cat metadata.json | jq '.["containerimage.digest"]' -r)"
      echo "image_digest=$DIGEST" >> "$GITHUB_OUTPUT"
    shell: bash
    env:
      TARGET: ${{ inputs.target }}
      IMAGE_NAME: ${{ inputs.image_name }}
      PUSH_IMAGE: ${{ inputs.push_image }}
      BUILD_ARCH: ${{ inputs.build_arch }}
  - name: docker logout
    if: ${{ always() }}
    env:
      DOCKER_REGISTRY: ${{ inputs.docker_registry }}
    shell: bash
    run: |
      docker logout $DOCKER_REGISTRY
