apiVersion: v1
kind: Namespace
metadata:
  name: authgear
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  namespace: authgear
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: authgear@example.com
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - selector: {}
        http01:
          ingress:
            class: nginx
