services:
  db:
    image: postgres-pg-partman:latest
    build:
      context: ../postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "15432:5432"

  redis:
    # Azure cache for Redis supports 6.0 only
    image: redis:6.0.20
    ports:
      - "16379:6379"
