name: CI - Pull Requests

on:
  pull_request:
    branches:
    - '*'
    - '!gh-pages'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  checks:
    uses: ./.github/workflows/run-checks.yaml
