name: Mirror

on: [push, delete]

jobs:
  mirror:
    if: ${{ github.repository == 'authgear/authgear-server' }}
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
      with:
        # Set fetch-depth: 0 to fetch all history for all branches and tags.
        # https://github.com/actions/checkout#:~:text=Set%20fetch%2Ddepth%3A%200%20to%20fetch%20all%20history%20for%20all%20branches%20and%20tags.
        fetch-depth: 0
    - name: Import GitHub Deploy Key of the mirror repository
      env:
        MIRROR_GITHUB_DEPLOY_KEY: ${{ secrets.MIRROR_GITHUB_DEPLOY_KEY_OURSKY }}
      run: |
        mkdir -p ~/.ssh
        printf "$MIRROR_GITHUB_DEPLOY_KEY" | base64 --decode > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        if [ -e ~/.ssh/known_hosts ]; then ssh-keygen -R github.com; fi
        ssh-keyscan github.com >> ~/.ssh/known_hosts
    - name: Mirror
      run: |
        export GIT_SSH_COMMAND="ssh -v -i ~/.ssh/id_ed25519"
        # The original command is
        #    git push --tags --force --prune "git@github.com:oursky/authgear-server.git" "refs/remotes/origin/*:refs/heads/*"
        #
        # It has been working so well, until 2025-01-23, git starts include refs/remotes/origin/HEAD in the expansion.
        # That would include refs/remotes/origin/HEAD:refs/heads/HEAD.
        # That means push a branch named HEAD in the mirror repository.
        # HEAD has a special meaning in Git, and it is obviously not suitable for a branch name.
        #
        # So we use `git show-ref` plus some filtering with awk and perl to filter out refs/remotes/origin/HEAD.
        # And build the `git push ...` command with xargs.
        git show-ref | awk '{ print $2 }' | perl -n -e 'if (/(^refs\/remotes\/origin\/(.+)$)/ ) { if ($2 != "HEAD") {  print "$1:refs/heads/$2\n" } }' | xargs -x git push --tags --force --prune "git@github.com:oursky/authgear-server.git"
    - name: Clean up
      if: ${{ always() }}
      run: |
        rm -f ~/.ssh/id_ed25519
