name: Do builds

on:
  workflow_call:

jobs:
  authgear-image-amd64:
    if: ${{ github.repository != 'oursky/authgear-server' }}
    runs-on: ubuntu-24.04
    env:
      PUSH_IMAGE: "${{ (github.repository == 'authgear/authgear-server' && github.event_name == 'push') && 'true' || 'false' }}"
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/build-image
      with:
        target: authgear
        image_name: quay.io/theauthgear/authgear-server
        push_image: "${{ env.PUSH_IMAGE }}"
        build_arch: amd64
        docker_registry: quay.io
        docker_username: "${{ env.PUSH_IMAGE == 'true' && secrets.QUAY_USERNAME || '' }}"
        docker_password: "${{ env.PUSH_IMAGE == 'true' && secrets.QUAY_ROBOT_TOKEN || '' }}"
  authgear-image-arm64:
    if: ${{ (github.repository == 'authgear/authgear-server' && github.event_name == 'push') }}
    runs-on: ubuntu-24.04
    env:
      PUSH_IMAGE: "${{ (github.repository == 'authgear/authgear-server' && github.event_name == 'push') && 'true' || 'false' }}"
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/build-image
      with:
        target: authgear
        image_name: quay.io/theauthgear/authgear-server
        push_image: "${{ env.PUSH_IMAGE }}"
        build_arch: arm64
        docker_registry: quay.io
        docker_username: "${{ env.PUSH_IMAGE == 'true' && secrets.QUAY_USERNAME || '' }}"
        docker_password: "${{ env.PUSH_IMAGE == 'true' && secrets.QUAY_ROBOT_TOKEN || '' }}"

  authgear-image:
    if: ${{ (github.repository == 'authgear/authgear-server' && github.event_name == 'push') }}
    runs-on: ubuntu-24.04
    needs: ["authgear-image-amd64", "authgear-image-arm64"]
    env:
      TARGET: authgear
      IMAGE_NAME: quay.io/theauthgear/authgear-server
      PUSH_IMAGE: "${{ (github.repository == 'authgear/authgear-server' && github.event_name == 'push') && 'true' || 'false' }}"
      SOURCE_ARCHS: arm64,amd64
    steps:
    - uses: actions/checkout@v4
    - name: docker login
      if: ${{ github.repository == 'authgear/authgear-server' && github.event_name == 'push' }}
      env:
        DOCKER_USERNAME: ${{ secrets.QUAY_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.QUAY_ROBOT_TOKEN }}
      run: |
        printf "$DOCKER_PASSWORD" | docker login --password-stdin --username "$DOCKER_USERNAME" quay.io
    - run: make tag-image SOURCE_ARCHS=$SOURCE_ARCHS IMAGE_NAME=$IMAGE_NAME
    - name: docker logout
      if: ${{ always() }}
      run: |
        docker logout quay.io


  portal-image-amd64:
    if: ${{ github.repository != 'oursky/authgear-server' }}
    runs-on: ubuntu-24.04
    env:
      PUSH_IMAGE: "${{ (github.repository == 'authgear/authgear-server' && github.event_name == 'push') && 'true' || 'false' }}"
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/build-image
      with:
        target: portal
        image_name: quay.io/theauthgear/authgear-portal
        push_image: "${{ env.PUSH_IMAGE }}"
        build_arch: amd64
        docker_registry: quay.io
        docker_username: "${{ env.PUSH_IMAGE == 'true' && secrets.QUAY_USERNAME || '' }}"
        docker_password: "${{ env.PUSH_IMAGE == 'true' && secrets.QUAY_ROBOT_TOKEN || '' }}"

  portal-image-arm64:
    if: ${{ (github.repository == 'authgear/authgear-server' && github.event_name == 'push') }}
    runs-on: ubuntu-24.04
    env:
      PUSH_IMAGE: "${{ (github.repository == 'authgear/authgear-server' && github.event_name == 'push') && 'true' || 'false' }}"
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/build-image
      with:
        target: portal
        image_name: quay.io/theauthgear/authgear-portal
        push_image: "${{ env.PUSH_IMAGE }}"
        build_arch: arm64
        docker_registry: quay.io
        docker_username: "${{ env.PUSH_IMAGE == 'true' && secrets.QUAY_USERNAME || '' }}"
        docker_password: "${{ env.PUSH_IMAGE == 'true' && secrets.QUAY_ROBOT_TOKEN || '' }}"

  portal-image:
    if: ${{ (github.repository == 'authgear/authgear-server' && github.event_name == 'push') }}
    runs-on: ubuntu-24.04
    needs: ["portal-image-amd64", "portal-image-arm64"]
    env:
      TARGET: authgear
      IMAGE_NAME: quay.io/theauthgear/authgear-portal
      PUSH_IMAGE: "${{ (github.repository == 'authgear/authgear-server' && github.event_name == 'push') && 'true' || 'false' }}"
      SOURCE_ARCHS: arm64,amd64
    steps:
    - uses: actions/checkout@v4
    - name: docker login
      if: ${{ github.repository == 'authgear/authgear-server' && github.event_name == 'push' }}
      env:
        DOCKER_USERNAME: ${{ secrets.QUAY_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.QUAY_ROBOT_TOKEN }}
      run: |
        printf "$DOCKER_PASSWORD" | docker login --password-stdin --username "$DOCKER_USERNAME" quay.io
    - run: make tag-image SOURCE_ARCHS=$SOURCE_ARCHS IMAGE_NAME=$IMAGE_NAME
    - name: docker logout
      if: ${{ always() }}
      run: |
        docker logout quay.io
