name: Test

on:
  push:
    branches:
      - '*'
      - '!gh-pages'
  pull_request:
    branches:
      - '*'
      - '!gh-pages'

jobs:
  test:
    name: Test
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.14.4"
      - uses: actions/setup-node@v1
        with:
          node-version: "12.18.0"
      - run: make vendor
      - run: make lint
        if: ${{ !cancelled() }}
      - run: make test
        if: ${{ !cancelled() }}
      - run: make check-tidy
        if: ${{ !cancelled() }}